steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/lisoceancolor/lisoceancolor-repo/olci-api',
        '.'
      ]

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', us-central1-docker.pkg.dev/lisoceancolor/lisoceancolor-repo/olci-api]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'olci-api',
        '--image',
        'us-central1-docker.pkg.dev/lisoceancolor/lisoceancolor-repo/olci-api',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]

# Optional: specify logs bucket if needed
logsBucket: 'gs://lisoceancolor-cloudbuild-logs'
